// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/games/Documents/Projetos/totem/totem/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/games/Documents/Projetos/totem/totem/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Totem Up Consultórios', appParameters);
});
require('c:/Users/games/Documents/Projetos/totem/totem/index.js');